package com.moss.error_reporting.api.jaxws;

import com.moss.error_reporting.api.ErrorReport;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class GetReportResponse {

    private ErrorReport Return;

    public ErrorReport getReturn() {
        return Return;
    }

    public void setReturn(ErrorReport Return) {
        this.Return = Return;
    }
}
