package com.moss.error_reporting.api.jaxws;

import com.moss.error_reporting.api.ReportId;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class GetReport {

    private ReportId arg0;

    public ReportId getArg0() {
        return arg0;
    }

    public void setArg0(ReportId arg0) {
        this.arg0 = arg0;
    }
}
