package com.moss.error_reporting.api.jaxws;

import com.moss.error_reporting.api.ErrorReportSummary;
import java.util.List;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class ListReportSummariesResponse {

    private List<ErrorReportSummary> Return;

    public List<ErrorReportSummary> getReturn() {
        return Return;
    }

    public void setReturn(List<ErrorReportSummary> Return) {
        this.Return = Return;
    }
}
