package com.moss.error_reporting.api.jaxws;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class ListReportSummaries {


}
