package com.moss.error_reporting.api.jaxws;

import com.moss.error_reporting.api.ReportId;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class SubmitReportResponse {

    private ReportId Return;

    public ReportId getReturn() {
        return Return;
    }

    public void setReturn(ReportId Return) {
        this.Return = Return;
    }
}
