package com.moss.error_reporting.api.jaxws;

import com.moss.error_reporting.api.ErrorReport;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class SubmitReport {

    private ErrorReport arg0;

    public ErrorReport getArg0() {
        return arg0;
    }

    public void setArg0(ErrorReport arg0) {
        this.arg0 = arg0;
    }
}
